### ISSUE TITLE
Exception installing all versions

### ISSUE THREAD

**Issue by juagarc4** [acquia/blt-project#22]
Hi all, 

I installed yesterday some bracnhes (stable and dev ones) of blt-project and It was fine.
Today I have tried it with all branches and I receive each time the follow error:

 Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/1356276-408--8.4.3.patch
                                                                                                                                                                               
  [Exception]                                                                                                                                                                      
  Cannot apply patch 1356276 - Allow profiles to provide a base/parent profile and load them in the correct order (https://www.drupal.org/files/issues/1356276-408--8.4.3.patch)!  
                                                                                                                                                                                   

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

[ExecStack]  Exit code 1  Time 01:32
[error]  Could not install Composer requirements. 

The last time i used the follow line:

composer create-project acquia/blt-project --no-interaction projectname

It makes drupal/blt-project completely unusable.

Thaanks in advance
Raul

**Comment by danepowell** [comment]
This is a bug with Lightning: https://www.drupal.org/project/lightning/issues/2934239

Since it completely breaks BLT project creation, I think we should consider a workaround, depending on how soon Lightning is going to push a new release. I'm bothered by how frequently this happens (I think this is the second core release in a row to have this problem), I don't like the idea of the project being so unstable. Unfortunately, I'm not sure what a good workaround / long-term fix would be short of pinning Drupal core versions.

**Comment by danepowell** [comment]
This should be fixed with the recent release of Lightning 2.2.7.
